In [1]:
import tushare as ts
pro = ts.pro_api('08faa79957b202b0827569041d9e39f6a092aab008802d94e08c7495')

df = pro.trade_cal(exchange='', 
                   start_date='20220501', 
                   end_date='20220531', 
#                    fields='exchange,cal_date,is_open,pretrade_date',
                   is_open='0')

In [3]:
import pandas as pd

import matplotlib.pyplot as plt

In [4]:
def get_data(code,start,end):
    df=pro.daily(ts_code=code,autype='qfq',start_date=start,end_date=end)
    print(df)
    df.index = pd.to_datetime(df.trade_date)
    #设置把日期作为索引
    #df['ma'] = 0.0  # Backtrader需要用到
    #df['openinterest'] = 0.0  # Backtrader需要用到
    #定义两个新的列ma和openinterest
    df = df[['open', 'high', 'low', 'close', 'vol']]
    #重新设置df取值，并返回df
    return df

In [9]:
df_zhongXinBank = get_data('601998.SH', '20220501', '20220531')

      ts_code trade_date  open  high   low  close  pre_close  change  pct_chg  \
0   601998.SH   20220531  4.66  4.67  4.63   4.65       4.65    0.00   0.0000
1   601998.SH   20220530  4.66  4.68  4.64   4.65       4.65    0.00   0.0000
2   601998.SH   20220527  4.64  4.66  4.62   4.65       4.63    0.02   0.4320
3   601998.SH   20220526  4.62  4.66  4.61   4.63       4.62    0.01   0.2165
4   601998.SH   20220525  4.58  4.63  4.57   4.62       4.58    0.04   0.8734
5   601998.SH   20220524  4.64  4.64  4.58   4.58       4.63   -0.05  -1.0799
6   601998.SH   20220523  4.64  4.65  4.62   4.63       4.64   -0.01  -0.2155
7   601998.SH   20220520  4.59  4.65  4.59   4.64       4.61    0.03   0.6508
8   601998.SH   20220519  4.58  4.63  4.56   4.61       4.62   -0.01  -0.2165
9   601998.SH   20220518  4.68  4.69  4.61   4.62       4.68   -0.06  -1.2821
10  601998.SH   20220517  4.69  4.69  4.64   4.68       4.68    0.00   0.0000
11  601998.SH   20220516  4.67  4.70  4.64   4.68       4.69   -0.01  -0.2132
12  601998.SH   20220513  4.68  4.71  4.65   4.69       4.67    0.02   0.4283
13  601998.SH   20220512  4.68  4.69  4.64   4.67       4.70   -0.03  -0.6383
14  601998.SH   20220511  4.71  4.73  4.67   4.70       4.71   -0.01  -0.2123
15  601998.SH   20220510  4.65  4.72  4.63   4.71       4.67    0.04   0.8565
16  601998.SH   20220509  4.62  4.71  4.59   4.67       4.64    0.03   0.6466
17  601998.SH   20220506  4.65  4.68  4.58   4.64       4.71   -0.07  -1.4862
18  601998.SH   20220505  4.80  4.82  4.68   4.71       5.03   -0.32  -6.3618

          vol      amount
0   199329.59   92688.456
1   172303.20   80291.698
2   213066.12   98912.850
3   237214.66  109991.196
4   196842.52   90631.219
5   235521.80  108670.164
6   219666.85  101730.733
7   354391.80  163968.940
8   397908.27  182209.774
9   232774.59  107720.020
10  202807.17   94707.079
11  227281.80  105961.660
12  257018.09  120351.066
13  174901.92   81619.920
14  245721.04  115444.741
15  297726.13  139518.179
16  300722.83  140164.632
17  475406.80  220479.463
18  958227.05  453115.069

In [34]:
df_ = pro.daily(ts_code='601998.SH',autype='qfq',start_date='20220501',end_date='20220531')

In [23]:
df_

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,601998.SH,20220531,4.66,4.67,4.63,4.65,4.65,0.00,0.0000,199329.59,92688.456
1,601998.SH,20220530,4.66,4.68,4.64,4.65,4.65,0.00,0.0000,172303.20,80291.698
2,601998.SH,20220527,4.64,4.66,4.62,4.65,4.63,0.02,0.4320,213066.12,98912.850
3,601998.SH,20220526,4.62,4.66,4.61,4.63,4.62,0.01,0.2165,237214.66,109991.196
4,601998.SH,20220525,4.58,4.63,4.57,4.62,4.58,0.04,0.8734,196842.52,90631.219
5,601998.SH,20220524,4.64,4.64,4.58,4.58,4.63,-0.05,-1.0799,235521.80,108670.164
6,601998.SH,20220523,4.64,4.65,4.62,4.63,4.64,-0.01,-0.2155,219666.85,101730.733
7,601998.SH,20220520,4.59,4.65,4.59,4.64,4.61,0.03,0.6508,354391.80,163968.940
8,601998.SH,20220519,4.58,4.63,4.56,4.61,4.62,-0.01,-0.2165,397908.27,182209.774
9,601998.SH,20220518,4.68,4.69,4.61,4.62,4.68,-0.06,-1.2821,232774.59,107720.020
10,601998.SH,20220517,4.69,4.69,4.64,4.68,4.68,0.00,0.0000,202807.17,94707.079
11,601998.SH,20220516,4.67,4.70,4.64,4.68,4.69,-0.01,-0.2132,227281.80,105961.660
12,601998.SH,20220513,4.68,4.71,4.65,4.69,4.67,0.02,0.4283,257018.09,120351.066
13,601998.SH,20220512,4.68,4.69,4.64,4.67,4.70,-0.03,-0.6383,174901.92,81619.920
14,601998.SH,20220511,4.71,4.73,4.67,4.70,4.71,-0.01,-0.2123,245721.04,115444.741
15,601998.SH,20220510,4.65,4.72,4.63,4.71,4.67,0.04,0.8565,297726.13,139518.179
16,601998.SH,20220509,4.62,4.71,4.59,4.67,4.64,0.03,0.6466,300722.83,140164.632
17,601998.SH,20220506,4.65,4.68,4.58,4.64,4.71,-0.07,-1.4862,475406.80,220479.463
18,601998.SH,20220505,4.80,4.82,4.68,4.71,5.03,-0.32,-6.3618,958227.05,453115.069

In [35]:
import time

df_['trade_date'] = pd.to_datetime(df_['trade_date'], format="%Y-%m-%d",errors='coerce')

In [36]:
df_['vol'] =df_['vol'].astype(int)

df_['amount'] =df_['amount'].astype(int)

In [37]:
df_.insert(loc=1, column='name',value = '中信银行')

In [42]:
df_ = df_.drop(columns='pre_close')

df_

,ts_code,name,trade_date,open,high,low,close,change,pct_chg,vol,amount
0,601998.SH,中信银行,2022-05-31,4.66,4.67,4.63,4.65,0.00,0.0000,199329,92688
1,601998.SH,中信银行,2022-05-30,4.66,4.68,4.64,4.65,0.00,0.0000,172303,80291
2,601998.SH,中信银行,2022-05-27,4.64,4.66,4.62,4.65,0.02,0.4320,213066,98912
3,601998.SH,中信银行,2022-05-26,4.62,4.66,4.61,4.63,0.01,0.2165,237214,109991
4,601998.SH,中信银行,2022-05-25,4.58,4.63,4.57,4.62,0.04,0.8734,196842,90631
5,601998.SH,中信银行,2022-05-24,4.64,4.64,4.58,4.58,-0.05,-1.0799,235521,108670
6,601998.SH,中信银行,2022-05-23,4.64,4.65,4.62,4.63,-0.01,-0.2155,219666,101730
7,601998.SH,中信银行,2022-05-20,4.59,4.65,4.59,4.64,0.03,0.6508,354391,163968
8,601998.SH,中信银行,2022-05-19,4.58,4.63,4.56,4.61,-0.01,-0.2165,397908,182209
9,601998.SH,中信银行,2022-05-18,4.68,4.69,4.61,4.62,-0.06,-1.2821,232774,107720
10,601998.SH,中信银行,2022-05-17,4.69,4.69,4.64,4.68,0.00,0.0000,202807,94707
11,601998.SH,中信银行,2022-05-16,4.67,4.70,4.64,4.68,-0.01,-0.2132,227281,105961
12,601998.SH,中信银行,2022-05-13,4.68,4.71,4.65,4.69,0.02,0.4283,257018,120351
13,601998.SH,中信银行,2022-05-12,4.68,4.69,4.64,4.67,-0.03,-0.6383,174901,81619
14,601998.SH,中信银行,2022-05-11,4.71,4.73,4.67,4.70,-0.01,-0.2123,245721,115444
15,601998.SH,中信银行,2022-05-10,4.65,4.72,4.63,4.71,0.04,0.8565,297726,139518
16,601998.SH,中信银行,2022-05-09,4.62,4.71,4.59,4.67,0.03,0.6466,300722,140164
17,601998.SH,中信银行,2022-05-06,4.65,4.68,4.58,4.64,-0.07,-1.4862,475406,220479
18,601998.SH,中信银行,2022-05-05,4.80,4.82,4.68,4.71,-0.32,-6.3618,958227,453115

In [44]:
df_.set_index('trade_date')

,ts_code,name,open,high,low,close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,
2022-05-31,601998.SH,中信银行,4.66,4.67,4.63,4.65,0.00,0.0000,199329,92688
2022-05-30,601998.SH,中信银行,4.66,4.68,4.64,4.65,0.00,0.0000,172303,80291
2022-05-27,601998.SH,中信银行,4.64,4.66,4.62,4.65,0.02,0.4320,213066,98912
2022-05-26,601998.SH,中信银行,4.62,4.66,4.61,4.63,0.01,0.2165,237214,109991
2022-05-25,601998.SH,中信银行,4.58,4.63,4.57,4.62,0.04,0.8734,196842,90631
2022-05-24,601998.SH,中信银行,4.64,4.64,4.58,4.58,-0.05,-1.0799,235521,108670
2022-05-23,601998.SH,中信银行,4.64,4.65,4.62,4.63,-0.01,-0.2155,219666,101730
2022-05-20,601998.SH,中信银行,4.59,4.65,4.59,4.64,0.03,0.6508,354391,163968
2022-05-19,601998.SH,中信银行,4.58,4.63,4.56,4.61,-0.01,-0.2165,397908,182209
2022-05-18,601998.SH,中信银行,4.68,4.69,4.61,4.62,-0.06,-1.2821,232774,107720
2022-05-17,601998.SH,中信银行,4.69,4.69,4.64,4.68,0.00,0.0000,202807,94707
2022-05-16,601998.SH,中信银行,4.67,4.70,4.64,4.68,-0.01,-0.2132,227281,105961
2022-05-13,601998.SH,中信银行,4.68,4.71,4.65,4.69,0.02,0.4283,257018,120351
2022-05-12,601998.SH,中信银行,4.68,4.69,4.64,4.67,-0.03,-0.6383,174901,81619
2022-05-11,601998.SH,中信银行,4.71,4.73,4.67,4.70,-0.01,-0.2123,245721,115444
2022-05-10,601998.SH,中信银行,4.65,4.72,4.63,4.71,0.04,0.8565,297726,139518
2022-05-09,601998.SH,中信银行,4.62,4.71,4.59,4.67,0.03,0.6466,300722,140164
2022-05-06,601998.SH,中信银行,4.65,4.68,4.58,4.64,-0.07,-1.4862,475406,220479
2022-05-05,601998.SH,中信银行,4.80,4.82,4.68,4.71,-0.32,-6.3618,958227,453115